---
title: '#ZaraChallenge: estructura y toma de decisiones de la arquitectura'
author: "Equipo Uno"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: 'journal'
    toc_depth: 4
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Prólogo {-}

Este documento describe detalladamente el paso a paso de la creación de la webapp para coincidir prendas y todo lo que involucra.

# Fundamentos

Para la webapp, hemos procedido en varias fases:

1. Entrenamiento de modelos con TensorFlow.
2. Recolección de datos.

También hemos tenido varias fases intermedias como la elaboración de documentación para cons

# Procesamiento de datos

En una primera fase lo que hicimos fue construir un script en R con el paquete `rvest` (situado en `./backend/scrap.r`) con el propósito de peinar la web de Zara y hallar enlaces relativos a las colecciones de ropa. Posteriormente hicimos modificaciones hasta quedar con una lista de casi 13.000 prendas para la construcción

# Futuro:

La base de datos, hoy por hoy, se sirve del formato `csv`, posteriormente habrá que pensar en un formato como Apache Parquet.